"use client";
import Head from "next/head";
import Home from "./Home";
import Org from "./org";
import Aboutme from "./Aboutme";
import WhatIdo from "./WhatIdo";

import Aos from "aos";
import { useEffect } from "react";

export default function App() {
  useEffect(() => {
    Aos.init({
      duration: 1000,
      once: false,
      easing: "ease", // default easing for AOS animations
    });
  }, []);
  return (
    <>
      <div>
        <Head>
          <title>Imtiaz Nayeem Shawon</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div className="bgi">
        <div className="bghome">
          <Home />
          <Org />
          <Aboutme />
          <WhatIdo/>
        </div>
      </div>
    </>
  );
}
