import Head from "next/head";
import SmallIntro from "./SmallIntro";
import Home from "./Home";
import About from "./About";
import Expertise from "./expertise";
import Projects from "./Projects";
import Contactme from "./Contactme";
export default function App() {
  return (
    <>
      <div>
        <Head>
          <title>Imtiaz Nayeem Shawon</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div className="bgi">
        <div className="bghome">
          <Home />
          <About />
          <SmallIntro />
          <Expertise />
          <Projects />
          <Contactme/>
        </div>
      </div>
    </>
  );
}
